server:
  port: 8080

# dev DB 설정
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/otboo
    username: otboo
    password: otboo
    driver-class-name: org.postgresql.Driver

# P6spy 로깅 레벨 설정
logging:
  level:
    p6spy: debug
    com.nimbusds.jwt: debug
    org.springframework.web.socket: debug