spring:
  application:
    name: otboo-alone
  profiles:
    active: ${SPRING_PROFILE:dev}
  config:
    import: optional:file:.env[.properties]
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        #        highlight_sql: true
        #        use_sql_comments: true
        format_sql: true
    open-in-view: false
jwt:
  issuer: otboo
  access-token:
    validity-seconds: 900 # 15분
  refresh-token:
    validity-seconds: 2592000 # 30일
  secret: ${JWT_SECRET:test-jwt-secret-key-for-test-should-be-long-enough}

logging:
  level:
    root: info